### ISSUE TITLE
Add unassign buttons to employed cats

### ISSUE THREAD

**Issue by 00f2ff** [N8python/potatoz2#2]
This will be useful when a player wants to remove only certain cats from their jobs and not all of them. One risk the current button introduces is that it can rob the player of their army temporarily.

**Comment by N8python** [comment]
Could you fork the repo and implement the remove cat buttons? Then I could review.

**Comment by 00f2ff** [comment]
I suggest learning a frontend framework to help you assign values to elements and keep the code tidier. Another thing you'll want to look into is using webpack or similar for import resolution to split the code up. It's going to be tough to add this feature because your code is not external developer-friendly (i.e. missing detailed comments, lack of documentation, etc.), and I don't want to have to learn how the entire codebase works to make the change.

That said, I'll make a PR, but instead of fixing this issue I'll write some helper functions that make your life easier.

**Comment by N8python** [comment]
Thank you. At the time I worked on Potatoz I didn’t know that such a thing as front end frameworks existed, and I wrote REALLY sloppy code. I’ll document it over the weekend to make in easier on external devs.

**Comment by pjlasl** [comment]
I added a + and - with the ability to select an amount. waiting on merge from N8python

**Comment by N8python** [comment]
This issue is nearly resolved - Once pjasl UI is merged, we will have incrementing + decrementing buttons for the cats.

**Comment by N8python** [comment]
I merged pjlasl's pull request. There are now increment + decrement buttons.
