### ISSUE TITLE
Patch price doesn't go down after reset.

### ISSUE THREAD

**Issue by AdamEdry** [N8python/potatoz2#5]
I tried out the game and clicked the creativity upgrade before I read the description so I tried resetting so I could see it again. After resetting the patch price did not go down and was 50 instead of 20 as it was when I first started the game.

**Comment by N8python** [comment]
Ah, I'll will fix this.

**Comment by AdamEdry** [comment]
Thanks!
I'm not sure if theres a prestige mechanic in this game that will cause me to soft reset. Will the higher base patch price affect me badly? I couldn't figure out what to clear in my browser to make the game completely reset.

**Comment by N8python** [comment]
No - The higher patch price will not have much meaning as the game goes on. It might be a bit harder, but by the second stage of the game, it won’t matter.

**Comment by N8python** [comment]
Potatoz also does not have prestige. It is a one play through game.

**Comment by N8python** [comment]
I fixed the bug - Patch price now resets to 20.
